name: Build ZMK firmware
run-name: '${{ github.ref_name }}: ${{ github.event.head_commit.message || github.event.pull_request.title || github.sha }}'
# on:
#   push:
#     branches-ignore:
#       - 'main'
#   pull_request:
#     branches-ignore:
#       - 'main'
on: workflow_dispatch

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
