name: Build ZMK firmware
run-name: '#${{ github.run_id }} - ${{ github.ref_name }}: ${{ github.event.push.head_commit.message }}'
on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3
